name: CI workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.13-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Create Venv & Install dependencies
        run: |
          uv venv
          uv sync

      - name: Run tests with coverage
        run: uv run pytest app/tests -v --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing

