name: CI workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.13-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # use latest

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Set up Python 3.13
        run: uv python install 3.13

      - name: Init UV
        run: uv init

      - name: Create Venv
        run: uv venv

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest -v --maxfail=1 --disable-warnings
        run: uv run pytest --cov=app --cov-report=term-missing

